apiVersion: v1
kind: ConfigMap
metadata:
  name: go-gate-config-map
  namespace: go-gate-ns
data:
  VERSION: "v0.0.2"
  DESCRIPTION: "This ConfigMap contains configuration data for the Go Gate application, including version information and other relevant settings."
  CORS: "*"