apiVersion: v1
kind: Secret
metadata:
  name: go-gate-secret
  namespace: go-gate-ns
type: Opaque
data:
  # Base64 encoded value of "my-secret-value"
  secret-key: bXktc2VjcmV0LXZhbHVl

---

# Suggested addition: A Docker registry secret for pulling private images
# kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=my-user --docker-password=dckr_pat_xxx --dry-run=client -o yaml
# apiVersion: v1
# data:
#   .dockerconfigjson: "base64 auth generate"
# kind: Secret
# metadata:
#   name: regcred
# type: kubernetes.io/dockerconfigjson