# receivers is entry point of observability data.
# collector receiver from a lot of resources, it may be application, agent or intermediates system via receivers plugin corresponding.
receivers:
  otlp: # OpenTelemetry Protocol
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

# exporters is end of pipelines, it responsibility sending data telemtry (traces, logs, metrics) to monitoring system, storage system, stats system
# structure pipelines: receiver -> processors -> exporters
exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

# processors is heart of pipelines. It handle data, tranforms, optimal or enrich
# It can be filter, sampling, batch
# add metadata, resource attributes
# tranforms or reformat data
processors:
  batch:
    timeout: 2s
    send_batch_size: 512
    send_batch_max_size: 1024

  memory_limiter:
    check_interval: 5s
    limit_mib: 2048
    spike_limit_mib: 512

  tail_sampling:
    decision_wait: 5s
    num_traces: 50000
    expected_new_traces_per_sec: 5000

    policies:
      - name: errors
        type: status_code
        status_code: { status_codes: [ERROR] }

      - name: very-slow
        type: latency
        latency: { threshold_ms: 5000 }

      - name: business-critical
        type: string_attribute
        string_attribute:
          key: http.route
          values: ["/complex", "/api-critical"]

      - name: minimal-sample
        type: probabilistic
        probabilistic: { sampling_percentage: 1 } # 1%

# extensions for Collector health monitoring, service discovery, or data forwarding, among others
extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter, tail_sampling]
      exporters: [otlp/jaeger]
