receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
    compression: gzip
    sending_queue:
      enabled: true
      queue_size: 512

  logging:
    loglevel: info

processors:
  batch:

extensions:
  health_check:
  zpages:

service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging]
