receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:
    timeout: 2s
    send_batch_size: 512
    send_batch_max_size: 1024

  tail_sampling:
    decision_wait: 5s
    num_traces: 50000
    expected_new_traces_per_sec: 5000

    policies:
      - name: errors
        type: status_code
        status_code: { status_codes: [ERROR] }

      - name: very-slow
        type: latency
        latency: { threshold_ms: 5000 }

      - name: business-critical
        type: string_attribute
        string_attribute:
          key: http.route
          values: ["/complex", "/api-critical"]

      - name: minimal-sample
        type: probabilistic
        probabilistic: { sampling_percentage: 0.1 }

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, logging]
