services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.138.0
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./collector-config.yaml:/etc/otel/config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "13133:13133" # Health check
      - "1777:1777" # pprof
      - "55679:55679" # zpages
      - "8888:8888"
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.60
    ports:
      - "16686:16686" # Jaeger UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true
