auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 1m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
      chunks:
        directory: /loki/chunks

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

limits_config:
  allow_structured_metadata: true

  # otlp_config:
  #   resource_attributes:
  #     attributes_config:
  #       - action: index_label
  #         regex: service.group
  #   scope_attributes:
  #     - action: drop
  #       attributes:
  #         - method.name
  #   log_attributes:
  #     - action: structured_metadata
  #       attributes:
  #         - user.id
  #     - action: drop
  #       regex: .*

common:
  path_prefix: /loki
  storage:
    filesystem:
      prefix: /loki
