// Code generated by "gocqlx/cmd/schemagen"; DO NOT EDIT.

package models

import (
	"github.com/scylladb/gocqlx/v2/table"
)

// Table models.
var (
	MutantData = table.New(table.Metadata{
		Name: "mutant_data",
		Columns: []string{
			"address",
			"first_name",
			"last_name",
			"picture_location",
		},
		PartKey: []string{
			"first_name",
			"last_name",
		},
		SortKey: []string{},
	})
)

type MutantDataStruct struct {
	Address         string
	FirstName       string
	LastName        string
	PictureLocation string
}
