services:
  scylla_node1:
    image: scylladb/scylla:2025.3
    container_name: scylla_node1
    command: --smp 2 --memory 2G --overprovisioned 1
    ports:
      - "9042:9042" # CQL
      - "7000:7000" # inter-node communication
      - "7001:7001" # TLS inter-node
      - "7199:7199" # JMX
    networks:
      scylla-cluster:
        ipv4_address: 172.28.1.2

  scylla_node2:
    image: scylladb/scylla:2025.3
    container_name: scylla_node2
    command: --smp 2 --memory 2G --overprovisioned 1 --seeds=scylla_node1
    networks:
      scylla-cluster:
        ipv4_address: 172.28.1.3

  scylla_node3:
    image: scylladb/scylla:2025.3
    container_name: scylla_node3
    command: --smp 2 --memory 2G --overprovisioned 1 --seeds=scylla_node1
    networks:
      scylla-cluster:
        ipv4_address: 172.28.1.4

networks:
  scylla-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
